### ISSUE TITLE
ModuleNotFoundError: No module named 'src'

### ISSUE THREAD

**Issue by ReddSpark1** [OpShin/opshin-starter-kit#4]
Just going through the steps for the starket kit. Have got Poetry shell running, and ran Poetry install. 

I ran `python3 scripts/build.py` from the main folder:
and got:

```
Traceback (most recent call last):
  File "D:\opshin-starter-kit\scripts\build.py", line 4, in <module>
    from src.on_chain import vesting
ModuleNotFoundError: No module named 'src'

```

This error is due to the /src folder not being in Python's path, which I believe can be rectified by adding (in my case):
`sys.path.append(r"D:/opshin-starter-kit") `

to the top of the build.py code.

But then this gave a new error:

```
from opshin.ledger.interval import *
ModuleNotFoundError: No module named 'opshin'
```

From reading around I believe the most pythonic thing to do would be to just have it all set up as proper pypy libraries that people can install using pip?

My sources:
https://wellsr.com/python/how-to-create-custom-modules-in-python/
https://stackoverflow.com/questions/68432247/absolute-relative-import-in-python-modulenotfounderror-and-more

**Comment by nielstron** [comment]
Hi @ReddSpark1, thanks for reaching out!

**Comment by nielstron** [comment]
I am not sure what precisely caused your error because opshin is in fact installed as a package when you run poetry install. Make sure to stay in the virtual environment created by poetry shell. Regarding the `src` missing in the path I'll look into that.

**Comment by ReddSpark1** [comment]
Yeah I can confirm I followed all the instructions, and am in the poetry shell after doing a Poetry install. I think it's to do with what is in the first link I referenced. Not sure if it's just an issue on windows.

**Comment by nielstron** [comment]
The first link references how to create custom modules with python... Both the starter kit and opshin *are* custom modules :) By running `poetry install` both should be installed. Can you try running `pip install -e  .` in the poetry shell?

**Comment by nielstron** [comment]
Please also paste the output of the setup commands that you ran and the full command + output of your failing call to script/build.py

**Comment by ReddSpark1** [comment]
```
D:\opshin-starter-kit> pip install -e  .
Obtaining file:///D:/opshin-starter-kit
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: click<9.0.0,>=8.1.3 in c:\users\xxxx\appdata\roaming\python\python311\site-packages (from opshin-starter-kit==0.1.0) (8.1.3)
Collecting opshin<0.13.0,>=0.12.0 (from opshin-starter-kit==0.1.0)
  Using cached opshin-0.12.5-py3-none-any.whl (66 kB)
INFO: pip is looking at multiple versions of opshin-starter-kit to determine which version is compatible with other requirements. This could take a while.
ERROR: Package 'opshin-starter-kit' requires a different Python: 3.11.2 not in '<3.11,>=3.8'

```

```
D:\opshin-starter-kit> poetry install
The currently activated Python version 3.11.2 is not supported by the project (>=3.8, <3.11).
Trying to find and use a compatible version.
Using python3 (3.10.11)
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: opshin-starter-kit (0.1.0)

```

```
D:\opshin-starter-kit> poetry shell
The currently activated Python version 3.11.2 is not supported by the project (>=3.8, <3.11).
Trying to find and use a compatible version.
Using python3 (3.10.11)
Spawning shell within C:\Users\xxxx\AppData\Local\pypoetry\Cache\virtualenvs\opshin-starter-kit-bL56sgcU-py3.10
PowerShell 7.3.4
(opshin-starter-kit-py3.10) 

```
python3 scripts/build.py - with `sys.path.append(r"D:/opshin-starter-kit")`  added to build.py file.
```
(opshin-starter-kit-py3.10) D:\opshin-starter-kit> python3 scripts/build.py
Traceback (most recent call last):
  File "D:\opshin-starter-kit\scripts\build.py", line 5, in <module>
    from src.on_chain import vesting
  File "D:\opshin-starter-kit\src\on_chain\vesting.py", line 1, in <module>
    from opshin.ledger.interval import *
ModuleNotFoundError: No module named 'opshin'
(opshin-starter-kit-py3.10) 
```
python3 scripts/build.py - _without_ `sys.path.append(r"D:/opshin-starter-kit")`  added to build.py file.
```
(opshin-starter-kit-py3.10) D:\opshin-starter-kit> python3 scripts/build.py
Traceback (most recent call last):
  File "D:\opshin-starter-kit\scripts\build.py", line 5, in <module>
    from src.on_chain import vesting
ModuleNotFoundError: No module named 'src'
(opshin-starter-kit-py3.10) PS D:\opshin-starter-kit> c:\users\xxxx\appdata\roaming\python\python311\scripts

```

**Comment by nielstron** [comment]
Thanks! @juliusfrost can you maybe have a look at this? Looks like a windows issue to me... Clearly the install command installs the opshin package so why would it be missing when running the script?

**Comment by nielstron** [comment]
Thanks! Check the first output:

> ERROR: Package 'opshin-starter-kit' requires a different Python: 3.11.2 not in '<3.11,>=3.8'

**Comment by nielstron** [comment]
I am very confused. @juliusfrost can you maybe have a look? Poetry correctly takes care of installing the correct python version and installs all required modules - yet opshin can not be found? Sounds very much like a windows issue to me.

**Comment by nielstron** [comment]
Might be an issue with poetry on windows?
https://stackoverflow.com/a/69601122

UPDATE: according to the OP of this thread it might  e an issue of using pyenv + poetry - are you using pyenv?
https://stackoverflow.com/q/63491371

An alternative approach would be to run these commands (using python 3.10!):

```
python3 --version
python3 -m pip install -e . 
```

I don't know what tools work well for python versioning on windows but if you are used to pyenv might be a good choice.

Alternative alternative is running this stuff in https://demeter.run which gives you a full blown proper environment based on non-windows in your browser :)

**Comment by juliusfrost** [comment]
Looking at the commands you posted, whenever you are invoking the command `python3`, you are using the default system installed python 3 (which in your case is python 3.11.2). What you want to be doing is using a python **virtual environment** which will isolate the dependencies from affecting your system python install and other projects. This is done with `poetry install` but you cannot just run `python3` afterwards because you won't use the poetry environment you just created. To do this you have to run python scripts with either, `poetry run python scripts/build.py` or run it in the shell with
```bash
poetry shell
# This must be run within the shell, python3 will refer to your system installation.
python scripts/build.py
```

A way to tell if you're using the correct python virtual environment is to run
```
python -m pip list
```
And then search for `opshin-starter-kit` in the output

**Comment by ReddSpark1** [comment]
Ok I can report the problem has now resolved itself. I did exactly the same steps as I did yesterday but this time it worked.

1. In between I did do a fresh re-install of Anaconda/Jupyter notebook as I had to for some machine learning stuff I'm currently doing, so that's the only thing that I can point to that could have fixed the problem. 

2. I definitely was in the poetry shell env both yesterday and today - just that today it worked

3.  python -m pip list just keeps telling me to upgrade my pip and nothing more (and when I try to upgrade it tells me I can't upgrade it from whithin the virtual env, and when I quit out of the env to upgrade it tells me it's already updated)

**Comment by ReddSpark1** [comment]
This is the correct output:

```
D:\opshin-starter-kit> poetry shell

The currently activated Python version 3.11.2 is not supported by the project (>=3.8, <3.11).
Trying to find and use a compatible version.
Using python3 (3.10.11)
Spawning shell within C:\Users\xxxx\AppData\Local\pypoetry\Cache\virtualenvs\opshin-starter-kit-bL56sgcU-py3.10
PowerShell 7.3.4

(opshin-starter-kit-py3.10) PS D:\opshin-starter-kit> python scripts/build.py
Wrote script artifacts to build\vesting/
(opshin-starter-kit-py3.10) PS D:\opshin-starter-kit>
```

**Comment by ReddSpark1** [comment]
This is the correct output:

```
D:\opshin-starter-kit> poetry shell

The currently activated Python version 3.11.2 is not supported by the project (>=3.8, <3.11).
Trying to find and use a compatible version.
Using python3 (3.10.11)
Spawning shell within C:\Users\xxxx\AppData\Local\pypoetry\Cache\virtualenvs\opshin-starter-kit-bL56sgcU-py3.10
PowerShell 7.3.4

(opshin-starter-kit-py3.10) PS D:\opshin-starter-kit> python scripts/build.py
Wrote script artifacts to build\vesting/
(opshin-starter-kit-py3.10) PS D:\opshin-starter-kit>
```

**Comment by nielstron** [comment]
Cool, glad that it worked out! Unfortunately we still don't know what caused this.. Will close this now

**Comment by juliusfrost** [comment]
> Ok I can report the problem has now resolved itself. I did exactly the same steps as I did yesterday but this time it worked.
> 
>   1. In between I did do a fresh re-install of Anaconda/Jupyter notebook as I had to for some machine learning stuff I'm currently doing, so that's the only thing that I can point to that could have fixed the problem.

Poetry and conda are usually discouraged to be used together. But if you have a conda environment currently active then poetry will try to use that environment instead of creating its own. So make sure to do `conda deactivate` before working with poetry.

>  2. I definitely was in the poetry shell env both yesterday and today - just that today it worked

Probably has to do with conda being in the mix making things confusing

>  3. python -m pip list just keeps telling me to upgrade my pip and nothing more (and when I try to upgrade it tells me I can't upgrade it from whithin the virtual env, and when I quit out of the env to upgrade it tells me it's already updated)

I suspect this was when you had a venv created but no dependencies installed. `poetry install` would have installed the dependencies in that venv but that was probably not the correct venv anyways.

**Comment by juliusfrost** [comment]
Also if you have anaconda installed, you should run
`conda config --set auto_activate_base false`

That way `poetry install` doesn't use the base environment by accident
